services:
  - type: web
    name: fruits-and-vegges-scan-ai
    runtime: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: bash start.sh
    healthCheckPath: /_stcore/health
    domains:
      - www.fruitsandveg.com
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
